Adding Meta Trait: Trait Count for Rarity Calculation
OpenRarity/open-rarity pull request #84
Opened 2022-10-14 21:31 UTC by vickygos

2022-10-14 23:58 UTC, amamujee commented
I modified the text a little

2022-10-17 17:19 UTC, theelderbeever requested changes
That was a big one... A couple comments with possible additions and nits. Nothing major.

2022-10-17 17:19 UTC, theelderbeever commented on open_rarity/resolver/testset_resolver.py
> +
`dry_run` doesn't quite feel right here... Maybe something like `to_console` and it still formats that csv but just prints to stdout?

2022-10-17 18:32 UTC, vickygos commented on open_rarity/models/collection.py
> +TRAIT_COUNT_ATTRIBUTE_NAME = "meta trait: trait_count"
Done: `TRAIT_COUNT_ATTRIBUTE_NAME = "meta_trait:trait_count"`

2022-10-17 20:05 UTC, grantli-os approved these changes

2022-10-17 21:54 UTC, theelderbeever approved these changes

2022-10-18 00:18 UTC, merged